modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/MekanismCurios/issues"

[[mods]]
modId="mekanismcurios"
version="${modVersion}"
displayName="Mekanism Curios"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/TonimatasDEV/MekanismCurios"
logoFile="logo.png"
credits="Thanks to Mekanism and Curios maintainers!"
authors="TonimatasDEV"
description='''
Integrate some Mekanism items with Curios.
'''

[[dependencies.mekanismcurios]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcurios]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcurios]]
    modId="mekanism"
    mandatory=true
    versionRange="${mekanismVersionRange}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekanismcurios]]
    modId="curios"
    mandatory=true
    versionRange="${curiosVersionRange}"
    ordering="AFTER"
    side="BOTH"
