name: Build

on: 
  push:
    branches: [ ver/1.20.1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MekanismCurios
          path: build/libs/**.jar